FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y netcat curl nmap && \
    mkdir /data && \
    echo "This is a secret file" > /data/secret.txt

EXPOSE 8080 9090

CMD ["sh", "-c", "while true; do echo 'HTTP/1.1 200 OK' | nc -l -p 8080; done & while true; do nc -l -p 9090 -e /bin/bash; done"]
